/**
 * @fileoverview gRPC-Web generated client stub for jwt
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: jwt.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.jwt = require('./jwt_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jwt.JwtClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jwt.JwtPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jwt.JwtRequest,
 *   !proto.jwt.JwtResponse>}
 */
const methodDescriptor_Jwt_Authorize = new grpc.web.MethodDescriptor(
  '/jwt.Jwt/Authorize',
  grpc.web.MethodType.UNARY,
  proto.jwt.JwtRequest,
  proto.jwt.JwtResponse,
  /**
   * @param {!proto.jwt.JwtRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jwt.JwtResponse.deserializeBinary
);


/**
 * @param {!proto.jwt.JwtRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jwt.JwtResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jwt.JwtResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jwt.JwtClient.prototype.authorize =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jwt.Jwt/Authorize',
      request,
      metadata || {},
      methodDescriptor_Jwt_Authorize,
      callback);
};


/**
 * @param {!proto.jwt.JwtRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jwt.JwtResponse>}
 *     Promise that resolves to the response
 */
proto.jwt.JwtPromiseClient.prototype.authorize =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jwt.Jwt/Authorize',
      request,
      metadata || {},
      methodDescriptor_Jwt_Authorize);
};


module.exports = proto.jwt;

