services:
  reactapp:
    image: reactapp
    build:
      context: C:\Users\Elect\WebstormProjects\WebSite\
    container_name: reactapp
    ports:
        - '3000:3000'
    
  grpcserver:
    image: grpcserver
    container_name: grpcserver
    build:
      context: .
      dockerfile: ./GrpcServer/Dockerfile
    ports:
        - 8080:80
        - 8081:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+443;http://+80
        - ASPNETCORE_HTTPS_PORT=443
        - ASPNETCORE_HTTP_PORT=80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/GrpcServer.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
        
  envoy:
    build: envoy/
    container_name: envoy
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/https.crt:/etc/ssl/certs/https.crt
      - ./envoy/key.pem:/etc/ssl/certs/key.pem