/**
 * @fileoverview gRPC-Web generated client stub for forecast
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: forecast.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.forecast = require('./forecast_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.forecast.ForecastClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.forecast.ForecastPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.forecast.ForecastMessage,
 *   !proto.forecast.ForecastReply>}
 */
const methodDescriptor_Forecast_Ask = new grpc.web.MethodDescriptor(
  '/forecast.Forecast/Ask',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.forecast.ForecastMessage,
  proto.forecast.ForecastReply,
  /**
   * @param {!proto.forecast.ForecastMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.forecast.ForecastReply.deserializeBinary
);


/**
 * @param {!proto.forecast.ForecastMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.forecast.ForecastReply>}
 *     The XHR Node Readable Stream
 */
proto.forecast.ForecastClient.prototype.ask =
    function (request, metadata, p) {
  return this.client_.serverStreaming(this.hostname_ +
      '/forecast.Forecast/Ask',
      request,
      metadata || {},
      methodDescriptor_Forecast_Ask);
};


/**
 * @param {!proto.forecast.ForecastMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.forecast.ForecastReply>}
 *     The XHR Node Readable Stream
 */
proto.forecast.ForecastPromiseClient.prototype.ask =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/forecast.Forecast/Ask',
      request,
      metadata || {},
      methodDescriptor_Forecast_Ask);
};


module.exports = proto.forecast;

